BUG: sync_selected_from_ui to handle IndexError
glue-viz/glue-jupyter pull request #270
Opened 2021-10-13 15:44 UTC by pllim

## Description

This PR is to:

* Fix spacetelescope/jdaviz#928

Workflow:

1. Download notebook from https://github.com/spacetelescope/jdat_notebooks/tree/main/notebooks/IFU_cube_continuum_fit
2. Only run the code in it to download data and load it into Cubeviz; ignore everything else.
3. In the top-left image viewer, create 9 subsets. All circles are fine. Overlap or not doesn't matter.
4. Delete Subset 2.
5. Delete Subset 7.
6. Delete Subset 9. Without this patch, you will see `IndexError`.
7. Bonus: Delete the rest of the subsets, bottom up. Without this patch, another error will appear when you delete the last one. I cannot tell if this patch renders #266 unnecessary or not. @eteq , you should double check.

Somewhat related: #266 , #293

Disclaimer: I don't grok the VueJS and Glue internals, so more elegant solution is welcome, but this patch should fix the immediate error reported over at Jdaviz.

2022-01-27 11:27 UTC, astrofrog requested changes
Thanks! Seems reasonable, can you fix the code style issues?

2022-01-27 15:41 UTC, pllim commented
Code style is fixed. I am not sure if the CI failures are related.

2022-02-22 19:57 UTC, rosteen commented
@astrofrog Just chiming in to say I tested this and it resolves a bug users were hitting in Jdaviz. Would be great to get it merged soon.

2022-02-22 22:50 UTC, astrofrog approved these changes

2022-02-22 22:50 UTC, merged