Only trigger event callbacks on their specified events
glue-viz/glue-jupyter pull request #279
Opened 2022-02-09 20:31 UTC by Carifio24

In order to accommodate multiple event callbacks, the mouse interact on the bqplot viewers currently listens for the set of events that is the union of all events specified via calls to `add_event_callback`. Currently, however, when any one of these events is detected, all callbacks are fired, regardless of whether or not it is one of their specified events.

To fix this issue, this PR modifies the viewer's mouse interact listener to check whether the current event is one of the callback's specified events before firing it.

2022-02-22 15:37 UTC, astrofrog commented
@pllim - since this could affect jdaviz, would you be able to check that all the buttons work correctly in imviz with this change?

2022-02-22 18:45 UTC, pllim requested changes
Alas, this broke blinking in Imviz and who knows what else.

2022-02-22 18:57 UTC, pllim commented
FWIW, there is example value of the variables for my session:

`data`

```python
{'event': 'keydown',
 'pixel': {'x': 777.96875, 'y': 76.609375},
 'domain': {'x': 3312.706444482224, 'y': 1707.172578671637},
 'code': 'KeyB',
 'charCode': 0,
 'key': 'b',
 'keyCode': 66,
 'altKey': False,
 'ctrlKey': False,
 'metaKey': False}
```

`callback`

```python
 functools.partial(<function ImvizImageView.on_mouse_or_key_event at ...,
                   <jdaviz.configs.imviz.plugins.viewers.ImvizImageView object at ...>)
```

2022-02-23 19:33 UTC, Carifio24 commented
So the reason this broke jdaviz is because I had forgotten to account for the fact that the items yielded by `CallbackContainer.__iter__` aren't the same as what are inserted via `append`. Hence the lookup in the events dictionary was always giving back an empty list.

I think my most recent commit should fix this. The `CallbackContainer` yields a new `partial` on every run through `__iter__`, so to get around this, the key that's stored in the events dictionary (when the callback is a method or a partial) is a tuple `(callback.__func__, (callback.__self__))`, which can easily be reproduced from a partial function `p` as `(p.func, p.args)`. This is then the key that's used in `_on_mouse_interaction`. @astrofrog does this seem like a reasonable way to handle this?

2022-02-23 19:53 UTC, pllim commented
Seems to work for me now in limited testing. Thanks!

2022-02-24 15:17 UTC, astrofrog approved these changes
Thanks!

2022-02-24 15:17 UTC, merged

2022-02-24 22:34 UTC, pllim commented
Oh, no. I think this broke Jdaviz after all. I should have ran the whole CI, my bad.

https://github.com/spacetelescope/jdaviz/runs/5325959132?check_suite_focus=true

2022-02-24 22:35 UTC, pllim commented
Is it possible to revert this and do a 0.11.1 release until we can figure it out? 🙏

2022-02-24 23:20 UTC, astrofrog commented
Can you provide more details of the failure? I can't do a bug fix immediately but will see if I can do it tomorrow. However I want to understand first whether it is actually an issue here or an issue in how jdaviz was using this functionality.

2022-02-24 23:21 UTC, astrofrog commented
Ah I see it is in https://github.com/spacetelescope/jdaviz/issues/1117 - @Carifio24 do you think this would be an easy fix?

2022-02-25 00:36 UTC, pllim commented
As you can see in spacetelescope/jdaviz#1117 ,  Specviz has a cube slicing plugin where you can click on the 1D spectrum and the cube image viewer would show the associated 2D image slice. That part of the code seems to be broken with this patch. It is unclear what is happening in the traceback without more digging.

2022-02-25 00:58 UTC, Carifio24 commented
Based on that traceback I think I see the problem (looks like it's here, and not with jdaviz), and I also think it should be a quick fix. I'll submit a fix tonight if I can, otherwise first thing tomorrow.

2022-02-25 01:00 UTC, pllim commented
Thank you! 🙏