Profile viewer as steps
glue-viz/glue-jupyter pull request #309
Opened 2022-04-19 15:16 UTC by kecnry

## Description

This accompanies https://github.com/glue-viz/glue/pull/2292 to expose the `as_steps` switch in the layer options widget and force the artist to redraw when changed.

2022-04-19 15:52 UTC, astrofrog requested changes
As mentioned in https://github.com/glue-viz/glue/pull/2292#issuecomment-1102814301, I think we should instead be implementing the logic of converting the profile into a stepped profile in the bqplot layer artist so that it would be analogous to the fact that this conversion is done in the layer artist for Matplotlib (in fact it is done inside Matplotlib because of the drawstype='steps' option).

2022-04-19 15:52 UTC, astrofrog commented on glue_jupyter/common/state_widgets/layer_profile.vue
> +            <v-switch label="Plot as steps/histogram" v-model="as_steps" />
I would avoid using the terminology 'histogram' here, maybe just use 'steps'

2022-04-22 11:19 UTC, astrofrog requested changes
Looks good and works great! Can you add a changelog entry? Also we will need to wait to merge this until a new version of glue-core is released, will try and do shortly once we merge the other PR.

2022-04-22 17:02 UTC, kecnry commented
Just noticed that this seems to break when adding a subset (within the bqplot steps logic)... we'll need to fix that before merging/releasing.

2022-05-19 09:33 UTC, astrofrog requested changes
Could you check that this works with glue-core 1.3.0 and if so bump the minimum glue-core version in setup.cfg? Once that is done I think we can merge this.

2022-08-24 16:52 UTC, kecnry commented
Sorry this fell off the radar for a little while.  I rebased, confirmed this works with glue 1.3+, and set that as a requirement in setup.cfg.

2022-08-24 19:44 UTC, astrofrog approved these changes
Looks great, thanks!

2022-08-26 16:39 UTC, merged