Scatter options
glue-viz/glue-jupyter pull request #458
Opened 2024-08-07 16:21 UTC by CyclingNinja

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

2025-02-13 16:18 UTC, dhomeier commented
visual test failure is related to solara fix in #475.
Might want to use some sort of pre-commit setup ;-)

2025-02-25 10:32 UTC, astrofrog requested changes
This is looking great! I just tried it out, and just have a couple of small comments below.

I think we should probably add a visual test for this - there are a few other existing visual tests, maybe you can copy one of those and try and make an example that exercises both the dashed lines and the vectors in one plot?

2025-02-25 14:57 UTC, dhomeier commented on glue_jupyter/bqplot/scatter/layer_artist.py
> +        print( "_update_scatter triggered")
also a flake8 failure here, but this looks like a leftover debugging print anyway?

2025-02-27 15:05 UTC, CyclingNinja commented on glue_jupyter/bqplot/scatter/layer_artist.py
> +        self.vector_lines.visible = False
for some reason changing this to use the imported LinesGL, stops the plot working at all?

2025-02-27 16:42 UTC, astrofrog commented on glue_jupyter/bqplot/scatter/layer_artist.py
> +        self.vector_lines.visible = False
Ok maybe it isn't robust to NaNs - just leave as-is then

2025-03-03 11:05 UTC, CyclingNinja commented on glue_jupyter/bqplot/scatter/layer_artist.py
> +        self.vector_lines.visible = False
ah this makes sense

2025-03-13 10:18 UTC, merged